CREATE TABLE board(
	bIdx BIGINT AUTO_INCREMENT PRIMARY KEY,
	mIdx BIGINT,
	bImage1 VARCHAR(255),
	imgPath VARCHAR(255),
	bContent TEXT,
	bHashtag VARCHAR(255),
	bRegdate DATE DEFAULT (CURRENT_DATE),
	bUpdate DATE,
	FOREIGN KEY (mIdx) REFERENCES member (mIdx)
);