CREATE TABLE board(
	bIdx BIGINT AUTO_INCREMENT PRIMARY KEY,
	mIdx BIGINT,
	bImage1 VARCHAR(255),
	imgPath VARCHAR(255),
	bContent TEXT,
	bHashtag VARCHAR(255),
	bLike BIGINT DEFAULT 0,
	bRegdate DATE DEFAULT (CURRENT_DATE),
	bUpdate DATE,
	FOREIGN KEY (mIdx) REFERENCES member (mIdx)
);

CREATE TABLE reply(
	re_Idx BIGINT PRIMARY KEY AUTO_INCREMENT,
	bIdx BIGINT,
	mIdx BIGINT,
	content TEXT,
	re_regdate DATE DEFAULT (CURRENT_DATE)
);